// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void GameTickHandler(ReducerEventContext ctx, SpacetimeDB.Types.GameTickSchedule schedule);
        public event GameTickHandler? OnGameTick;

        public void GameTick(SpacetimeDB.Types.GameTickSchedule schedule)
        {
            conn.InternalCallReducer(new Reducer.GameTick(schedule), this.SetCallReducerFlags.GameTickFlags);
        }

        public bool InvokeGameTick(ReducerEventContext ctx, Reducer.GameTick args)
        {
            if (OnGameTick == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnGameTick(
                ctx,
                args.Schedule
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class GameTick : Reducer, IReducerArgs
        {
            [DataMember(Name = "_schedule")]
            public GameTickSchedule Schedule;

            public GameTick(GameTickSchedule Schedule)
            {
                this.Schedule = Schedule;
            }

            public GameTick()
            {
                this.Schedule = new();
            }

            string IReducerArgs.ReducerName => "GameTick";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags GameTickFlags;
        public void GameTick(CallReducerFlags flags) => GameTickFlags = flags;
    }
}
