// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void IssueAttackHandler(ReducerEventContext ctx, SpacetimeDB.Types.TargetKind targetKind, ulong targetId);
        public event IssueAttackHandler? OnIssueAttack;

        public void IssueAttack(SpacetimeDB.Types.TargetKind targetKind, ulong targetId)
        {
            conn.InternalCallReducer(new Reducer.IssueAttack(targetKind, targetId), this.SetCallReducerFlags.IssueAttackFlags);
        }

        public bool InvokeIssueAttack(ReducerEventContext ctx, Reducer.IssueAttack args)
        {
            if (OnIssueAttack == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnIssueAttack(
                ctx,
                args.TargetKind,
                args.TargetId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class IssueAttack : Reducer, IReducerArgs
        {
            [DataMember(Name = "targetKind")]
            public TargetKind TargetKind;
            [DataMember(Name = "targetId")]
            public ulong TargetId;

            public IssueAttack(
                TargetKind TargetKind,
                ulong TargetId
            )
            {
                this.TargetKind = TargetKind;
                this.TargetId = TargetId;
            }

            public IssueAttack()
            {
            }

            string IReducerArgs.ReducerName => "IssueAttack";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags IssueAttackFlags;
        public void IssueAttack(CallReducerFlags flags) => IssueAttackFlags = flags;
    }
}
