// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void JoinLobbyHandler(ReducerEventContext ctx, string name);
        public event JoinLobbyHandler? OnJoinLobby;

        public void JoinLobby(string name)
        {
            conn.InternalCallReducer(new Reducer.JoinLobby(name), this.SetCallReducerFlags.JoinLobbyFlags);
        }

        public bool InvokeJoinLobby(ReducerEventContext ctx, Reducer.JoinLobby args)
        {
            if (OnJoinLobby == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnJoinLobby(
                ctx,
                args.Name
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class JoinLobby : Reducer, IReducerArgs
        {
            [DataMember(Name = "name")]
            public string Name;

            public JoinLobby(string Name)
            {
                this.Name = Name;
            }

            public JoinLobby()
            {
                this.Name = "";
            }

            string IReducerArgs.ReducerName => "JoinLobby";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags JoinLobbyFlags;
        public void JoinLobby(CallReducerFlags flags) => JoinLobbyFlags = flags;
    }
}
