// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void MoveToPositionHandler(ReducerEventContext ctx, float x, float y, float z);
        public event MoveToPositionHandler? OnMoveToPosition;

        public void MoveToPosition(float x, float y, float z)
        {
            conn.InternalCallReducer(new Reducer.MoveToPosition(x, y, z), this.SetCallReducerFlags.MoveToPositionFlags);
        }

        public bool InvokeMoveToPosition(ReducerEventContext ctx, Reducer.MoveToPosition args)
        {
            if (OnMoveToPosition == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnMoveToPosition(
                ctx,
                args.X,
                args.Y,
                args.Z
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class MoveToPosition : Reducer, IReducerArgs
        {
            [DataMember(Name = "x")]
            public float X;
            [DataMember(Name = "y")]
            public float Y;
            [DataMember(Name = "z")]
            public float Z;

            public MoveToPosition(
                float X,
                float Y,
                float Z
            )
            {
                this.X = X;
                this.Y = Y;
                this.Z = Z;
            }

            public MoveToPosition()
            {
            }

            string IReducerArgs.ReducerName => "MoveToPosition";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags MoveToPositionFlags;
        public void MoveToPosition(CallReducerFlags flags) => MoveToPositionFlags = flags;
    }
}
