// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RegisterProfileHandler(ReducerEventContext ctx, string username);
        public event RegisterProfileHandler? OnRegisterProfile;

        public void RegisterProfile(string username)
        {
            conn.InternalCallReducer(new Reducer.RegisterProfile(username), this.SetCallReducerFlags.RegisterProfileFlags);
        }

        public bool InvokeRegisterProfile(ReducerEventContext ctx, Reducer.RegisterProfile args)
        {
            if (OnRegisterProfile == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnRegisterProfile(
                ctx,
                args.Username
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RegisterProfile : Reducer, IReducerArgs
        {
            [DataMember(Name = "username")]
            public string Username;

            public RegisterProfile(string Username)
            {
                this.Username = Username;
            }

            public RegisterProfile()
            {
                this.Username = "";
            }

            string IReducerArgs.ReducerName => "RegisterProfile";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags RegisterProfileFlags;
        public void RegisterProfile(CallReducerFlags flags) => RegisterProfileFlags = flags;
    }
}
