// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ResetMatchHandler(ReducerEventContext ctx);
        public event ResetMatchHandler? OnResetMatch;

        public void ResetMatch()
        {
            conn.InternalCallReducer(new Reducer.ResetMatch(), this.SetCallReducerFlags.ResetMatchFlags);
        }

        public bool InvokeResetMatch(ReducerEventContext ctx, Reducer.ResetMatch args)
        {
            if (OnResetMatch == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnResetMatch(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ResetMatch : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "ResetMatch";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ResetMatchFlags;
        public void ResetMatch(CallReducerFlags flags) => ResetMatchFlags = flags;
    }
}
