// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SelectTeamHandler(ReducerEventContext ctx, SpacetimeDB.Types.Team team);
        public event SelectTeamHandler? OnSelectTeam;

        public void SelectTeam(SpacetimeDB.Types.Team team)
        {
            conn.InternalCallReducer(new Reducer.SelectTeam(team), this.SetCallReducerFlags.SelectTeamFlags);
        }

        public bool InvokeSelectTeam(ReducerEventContext ctx, Reducer.SelectTeam args)
        {
            if (OnSelectTeam == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSelectTeam(
                ctx,
                args.Team
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SelectTeam : Reducer, IReducerArgs
        {
            [DataMember(Name = "team")]
            public Team Team;

            public SelectTeam(Team Team)
            {
                this.Team = Team;
            }

            public SelectTeam()
            {
            }

            string IReducerArgs.ReducerName => "SelectTeam";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SelectTeamFlags;
        public void SelectTeam(CallReducerFlags flags) => SelectTeamFlags = flags;
    }
}
