// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetReadyHandler(ReducerEventContext ctx, bool ready);
        public event SetReadyHandler? OnSetReady;

        public void SetReady(bool ready)
        {
            conn.InternalCallReducer(new Reducer.SetReady(ready), this.SetCallReducerFlags.SetReadyFlags);
        }

        public bool InvokeSetReady(ReducerEventContext ctx, Reducer.SetReady args)
        {
            if (OnSetReady == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSetReady(
                ctx,
                args.Ready
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SetReady : Reducer, IReducerArgs
        {
            [DataMember(Name = "ready")]
            public bool Ready;

            public SetReady(bool Ready)
            {
                this.Ready = Ready;
            }

            public SetReady()
            {
            }

            string IReducerArgs.ReducerName => "SetReady";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SetReadyFlags;
        public void SetReady(CallReducerFlags flags) => SetReadyFlags = flags;
    }
}
