// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Champion
    {
        [DataMember(Name = "Id")]
        public ulong Id;
        [DataMember(Name = "OwnerIdentity")]
        public SpacetimeDB.Identity OwnerIdentity;
        [DataMember(Name = "Team")]
        public Team Team;
        [DataMember(Name = "Name")]
        public string Name;
        [DataMember(Name = "Position")]
        public DbVec3 Position;
        [DataMember(Name = "Destination")]
        public DbVec3 Destination;
        [DataMember(Name = "MoveSpeed")]
        public float MoveSpeed;
        [DataMember(Name = "State")]
        public ChampionState State;
        [DataMember(Name = "Health")]
        public float Health;
        [DataMember(Name = "MaxHealth")]
        public float MaxHealth;
        [DataMember(Name = "Mana")]
        public float Mana;
        [DataMember(Name = "MaxMana")]
        public float MaxMana;
        [DataMember(Name = "AttackTargetKind")]
        public TargetKind AttackTargetKind;
        [DataMember(Name = "AttackTargetId")]
        public ulong AttackTargetId;
        [DataMember(Name = "LastAttackTime")]
        public double LastAttackTime;
        [DataMember(Name = "AttackRange")]
        public float AttackRange;
        [DataMember(Name = "AttackDamage")]
        public float AttackDamage;
        [DataMember(Name = "AttackCooldown")]
        public float AttackCooldown;
        [DataMember(Name = "DeathTime")]
        public double DeathTime;
        [DataMember(Name = "RespawnDuration")]
        public float RespawnDuration;

        public Champion(
            ulong Id,
            SpacetimeDB.Identity OwnerIdentity,
            Team Team,
            string Name,
            DbVec3 Position,
            DbVec3 Destination,
            float MoveSpeed,
            ChampionState State,
            float Health,
            float MaxHealth,
            float Mana,
            float MaxMana,
            TargetKind AttackTargetKind,
            ulong AttackTargetId,
            double LastAttackTime,
            float AttackRange,
            float AttackDamage,
            float AttackCooldown,
            double DeathTime,
            float RespawnDuration
        )
        {
            this.Id = Id;
            this.OwnerIdentity = OwnerIdentity;
            this.Team = Team;
            this.Name = Name;
            this.Position = Position;
            this.Destination = Destination;
            this.MoveSpeed = MoveSpeed;
            this.State = State;
            this.Health = Health;
            this.MaxHealth = MaxHealth;
            this.Mana = Mana;
            this.MaxMana = MaxMana;
            this.AttackTargetKind = AttackTargetKind;
            this.AttackTargetId = AttackTargetId;
            this.LastAttackTime = LastAttackTime;
            this.AttackRange = AttackRange;
            this.AttackDamage = AttackDamage;
            this.AttackCooldown = AttackCooldown;
            this.DeathTime = DeathTime;
            this.RespawnDuration = RespawnDuration;
        }

        public Champion()
        {
            this.Name = "";
            this.Position = new();
            this.Destination = new();
        }
    }
}
