// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Config
    {
        [DataMember(Name = "Id")]
        public uint Id;
        [DataMember(Name = "MoveSpeed")]
        public float MoveSpeed;
        [DataMember(Name = "AttackRange")]
        public float AttackRange;
        [DataMember(Name = "AttackDamage")]
        public float AttackDamage;
        [DataMember(Name = "AttackCooldown")]
        public float AttackCooldown;
        [DataMember(Name = "RespawnDuration")]
        public float RespawnDuration;
        [DataMember(Name = "ChampMaxHealth")]
        public float ChampMaxHealth;
        [DataMember(Name = "ChampMaxMana")]
        public float ChampMaxMana;
        [DataMember(Name = "RadiantSpawn")]
        public DbVec3 RadiantSpawn;
        [DataMember(Name = "DireSpawn")]
        public DbVec3 DireSpawn;
        [DataMember(Name = "CreepMoveSpeed")]
        public float CreepMoveSpeed;
        [DataMember(Name = "CreepAttackRange")]
        public float CreepAttackRange;
        [DataMember(Name = "CreepAttackDamage")]
        public float CreepAttackDamage;
        [DataMember(Name = "CreepAttackCooldown")]
        public float CreepAttackCooldown;
        [DataMember(Name = "CreepMaxHealth")]
        public float CreepMaxHealth;
        [DataMember(Name = "CreepWaveIntervalSec")]
        public float CreepWaveIntervalSec;
        [DataMember(Name = "NeutralMoveSpeed")]
        public float NeutralMoveSpeed;
        [DataMember(Name = "NeutralAttackRange")]
        public float NeutralAttackRange;
        [DataMember(Name = "NeutralAttackDamage")]
        public float NeutralAttackDamage;
        [DataMember(Name = "NeutralAttackCooldown")]
        public float NeutralAttackCooldown;
        [DataMember(Name = "NeutralMaxHealth")]
        public float NeutralMaxHealth;
        [DataMember(Name = "NeutralRespawnSec")]
        public float NeutralRespawnSec;
        [DataMember(Name = "TowerMaxHealth")]
        public float TowerMaxHealth;
        [DataMember(Name = "TowerAttackDamage")]
        public float TowerAttackDamage;
        [DataMember(Name = "TowerAttackRange")]
        public float TowerAttackRange;
        [DataMember(Name = "TowerAttackCooldown")]
        public float TowerAttackCooldown;
        [DataMember(Name = "ThroneMaxHealth")]
        public float ThroneMaxHealth;

        public Config(
            uint Id,
            float MoveSpeed,
            float AttackRange,
            float AttackDamage,
            float AttackCooldown,
            float RespawnDuration,
            float ChampMaxHealth,
            float ChampMaxMana,
            DbVec3 RadiantSpawn,
            DbVec3 DireSpawn,
            float CreepMoveSpeed,
            float CreepAttackRange,
            float CreepAttackDamage,
            float CreepAttackCooldown,
            float CreepMaxHealth,
            float CreepWaveIntervalSec,
            float NeutralMoveSpeed,
            float NeutralAttackRange,
            float NeutralAttackDamage,
            float NeutralAttackCooldown,
            float NeutralMaxHealth,
            float NeutralRespawnSec,
            float TowerMaxHealth,
            float TowerAttackDamage,
            float TowerAttackRange,
            float TowerAttackCooldown,
            float ThroneMaxHealth
        )
        {
            this.Id = Id;
            this.MoveSpeed = MoveSpeed;
            this.AttackRange = AttackRange;
            this.AttackDamage = AttackDamage;
            this.AttackCooldown = AttackCooldown;
            this.RespawnDuration = RespawnDuration;
            this.ChampMaxHealth = ChampMaxHealth;
            this.ChampMaxMana = ChampMaxMana;
            this.RadiantSpawn = RadiantSpawn;
            this.DireSpawn = DireSpawn;
            this.CreepMoveSpeed = CreepMoveSpeed;
            this.CreepAttackRange = CreepAttackRange;
            this.CreepAttackDamage = CreepAttackDamage;
            this.CreepAttackCooldown = CreepAttackCooldown;
            this.CreepMaxHealth = CreepMaxHealth;
            this.CreepWaveIntervalSec = CreepWaveIntervalSec;
            this.NeutralMoveSpeed = NeutralMoveSpeed;
            this.NeutralAttackRange = NeutralAttackRange;
            this.NeutralAttackDamage = NeutralAttackDamage;
            this.NeutralAttackCooldown = NeutralAttackCooldown;
            this.NeutralMaxHealth = NeutralMaxHealth;
            this.NeutralRespawnSec = NeutralRespawnSec;
            this.TowerMaxHealth = TowerMaxHealth;
            this.TowerAttackDamage = TowerAttackDamage;
            this.TowerAttackRange = TowerAttackRange;
            this.TowerAttackCooldown = TowerAttackCooldown;
            this.ThroneMaxHealth = ThroneMaxHealth;
        }

        public Config()
        {
            this.RadiantSpawn = new();
            this.DireSpawn = new();
        }
    }
}
