// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Creep
    {
        [DataMember(Name = "Id")]
        public ulong Id;
        [DataMember(Name = "Team")]
        public Team Team;
        [DataMember(Name = "Type")]
        public CreepType Type;
        [DataMember(Name = "Lane")]
        public Lane Lane;
        [DataMember(Name = "Position")]
        public DbVec3 Position;
        [DataMember(Name = "Destination")]
        public DbVec3 Destination;
        [DataMember(Name = "MoveSpeed")]
        public float MoveSpeed;
        [DataMember(Name = "Health")]
        public float Health;
        [DataMember(Name = "MaxHealth")]
        public float MaxHealth;
        [DataMember(Name = "AttackRange")]
        public float AttackRange;
        [DataMember(Name = "AttackDamage")]
        public float AttackDamage;
        [DataMember(Name = "AttackCooldown")]
        public float AttackCooldown;
        [DataMember(Name = "State")]
        public CreepState State;
        [DataMember(Name = "AttackTargetKind")]
        public TargetKind AttackTargetKind;
        [DataMember(Name = "AttackTargetId")]
        public ulong AttackTargetId;
        [DataMember(Name = "LastAttackTime")]
        public double LastAttackTime;
        [DataMember(Name = "DeathTime")]
        public double DeathTime;
        [DataMember(Name = "CampId")]
        public ulong CampId;
        [DataMember(Name = "WaypointIndex")]
        public int WaypointIndex;

        public Creep(
            ulong Id,
            Team Team,
            CreepType Type,
            Lane Lane,
            DbVec3 Position,
            DbVec3 Destination,
            float MoveSpeed,
            float Health,
            float MaxHealth,
            float AttackRange,
            float AttackDamage,
            float AttackCooldown,
            CreepState State,
            TargetKind AttackTargetKind,
            ulong AttackTargetId,
            double LastAttackTime,
            double DeathTime,
            ulong CampId,
            int WaypointIndex
        )
        {
            this.Id = Id;
            this.Team = Team;
            this.Type = Type;
            this.Lane = Lane;
            this.Position = Position;
            this.Destination = Destination;
            this.MoveSpeed = MoveSpeed;
            this.Health = Health;
            this.MaxHealth = MaxHealth;
            this.AttackRange = AttackRange;
            this.AttackDamage = AttackDamage;
            this.AttackCooldown = AttackCooldown;
            this.State = State;
            this.AttackTargetKind = AttackTargetKind;
            this.AttackTargetId = AttackTargetId;
            this.LastAttackTime = LastAttackTime;
            this.DeathTime = DeathTime;
            this.CampId = CampId;
            this.WaypointIndex = WaypointIndex;
        }

        public Creep()
        {
            this.Position = new();
            this.Destination = new();
        }
    }
}
