// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class DbVec3
    {
        [DataMember(Name = "X")]
        public float X;
        [DataMember(Name = "Y")]
        public float Y;
        [DataMember(Name = "Z")]
        public float Z;

        public DbVec3(
            float X,
            float Y,
            float Z
        )
        {
            this.X = X;
            this.Y = Y;
            this.Z = Z;
        }

        public DbVec3()
        {
        }
    }
}
