// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class GameState
    {
        [DataMember(Name = "Id")]
        public uint Id;
        [DataMember(Name = "Phase")]
        public GamePhase Phase;
        [DataMember(Name = "WinnerTeam")]
        public Team WinnerTeam;
        [DataMember(Name = "Countdown")]
        public int Countdown;

        public GameState(
            uint Id,
            GamePhase Phase,
            Team WinnerTeam,
            int Countdown
        )
        {
            this.Id = Id;
            this.Phase = Phase;
            this.WinnerTeam = WinnerTeam;
            this.Countdown = Countdown;
        }

        public GameState()
        {
        }
    }
}
