// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class LobbyPlayer
    {
        [DataMember(Name = "PlayerId")]
        public SpacetimeDB.Identity PlayerId;
        [DataMember(Name = "Name")]
        public string Name;
        [DataMember(Name = "Team")]
        public Team Team;
        [DataMember(Name = "IsReady")]
        public bool IsReady;
        [DataMember(Name = "IsConnected")]
        public bool IsConnected;

        public LobbyPlayer(
            SpacetimeDB.Identity PlayerId,
            string Name,
            Team Team,
            bool IsReady,
            bool IsConnected
        )
        {
            this.PlayerId = PlayerId;
            this.Name = Name;
            this.Team = Team;
            this.IsReady = IsReady;
            this.IsConnected = IsConnected;
        }

        public LobbyPlayer()
        {
            this.Name = "";
        }
    }
}
