// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Structure
    {
        [DataMember(Name = "Id")]
        public ulong Id;
        [DataMember(Name = "Team")]
        public Team Team;
        [DataMember(Name = "Type")]
        public StructureType Type;
        [DataMember(Name = "Lane")]
        public Lane Lane;
        [DataMember(Name = "Position")]
        public DbVec3 Position;
        [DataMember(Name = "Health")]
        public float Health;
        [DataMember(Name = "MaxHealth")]
        public float MaxHealth;
        [DataMember(Name = "AttackDamage")]
        public float AttackDamage;
        [DataMember(Name = "AttackRange")]
        public float AttackRange;
        [DataMember(Name = "AttackCooldown")]
        public float AttackCooldown;
        [DataMember(Name = "LastAttackTime")]
        public double LastAttackTime;
        [DataMember(Name = "AttackTargetId")]
        public ulong AttackTargetId;
        [DataMember(Name = "AttackTargetKind")]
        public TargetKind AttackTargetKind;
        [DataMember(Name = "IsDestroyed")]
        public bool IsDestroyed;

        public Structure(
            ulong Id,
            Team Team,
            StructureType Type,
            Lane Lane,
            DbVec3 Position,
            float Health,
            float MaxHealth,
            float AttackDamage,
            float AttackRange,
            float AttackCooldown,
            double LastAttackTime,
            ulong AttackTargetId,
            TargetKind AttackTargetKind,
            bool IsDestroyed
        )
        {
            this.Id = Id;
            this.Team = Team;
            this.Type = Type;
            this.Lane = Lane;
            this.Position = Position;
            this.Health = Health;
            this.MaxHealth = MaxHealth;
            this.AttackDamage = AttackDamage;
            this.AttackRange = AttackRange;
            this.AttackCooldown = AttackCooldown;
            this.LastAttackTime = LastAttackTime;
            this.AttackTargetId = AttackTargetId;
            this.AttackTargetKind = AttackTargetKind;
            this.IsDestroyed = IsDestroyed;
        }

        public Structure()
        {
            this.Position = new();
        }
    }
}
