// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class UserProfile
    {
        [DataMember(Name = "PlayerId")]
        public SpacetimeDB.Identity PlayerId;
        [DataMember(Name = "Username")]
        public string Username;

        public UserProfile(
            SpacetimeDB.Identity PlayerId,
            string Username
        )
        {
            this.PlayerId = PlayerId;
            this.Username = Username;
        }

        public UserProfile()
        {
            this.Username = "";
        }
    }
}
