// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ChampionHandle : RemoteTableHandle<EventContext, Champion>
        {
            protected override string RemoteTableName => "Champion";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Champion row) => row.Id;

                public IdUniqueIndex(ChampionHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal ChampionHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(Champion row) => row.Id;
        }

        public readonly ChampionHandle Champion;
    }

    public sealed class ChampionCols
    {
        public global::SpacetimeDB.Col<Champion, ulong> Id { get; }
        public global::SpacetimeDB.Col<Champion, SpacetimeDB.Identity> OwnerIdentity { get; }
        public global::SpacetimeDB.Col<Champion, Team> Team { get; }
        public global::SpacetimeDB.Col<Champion, string> Name { get; }
        public global::SpacetimeDB.Col<Champion, DbVec3> Position { get; }
        public global::SpacetimeDB.Col<Champion, DbVec3> Destination { get; }
        public global::SpacetimeDB.Col<Champion, float> MoveSpeed { get; }
        public global::SpacetimeDB.Col<Champion, ChampionState> State { get; }
        public global::SpacetimeDB.Col<Champion, float> Health { get; }
        public global::SpacetimeDB.Col<Champion, float> MaxHealth { get; }
        public global::SpacetimeDB.Col<Champion, float> Mana { get; }
        public global::SpacetimeDB.Col<Champion, float> MaxMana { get; }
        public global::SpacetimeDB.Col<Champion, TargetKind> AttackTargetKind { get; }
        public global::SpacetimeDB.Col<Champion, ulong> AttackTargetId { get; }
        public global::SpacetimeDB.Col<Champion, double> LastAttackTime { get; }
        public global::SpacetimeDB.Col<Champion, float> AttackRange { get; }
        public global::SpacetimeDB.Col<Champion, float> AttackDamage { get; }
        public global::SpacetimeDB.Col<Champion, float> AttackCooldown { get; }
        public global::SpacetimeDB.Col<Champion, double> DeathTime { get; }
        public global::SpacetimeDB.Col<Champion, float> RespawnDuration { get; }

        public ChampionCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<Champion, ulong>(tableName, "Id");
            OwnerIdentity = new global::SpacetimeDB.Col<Champion, SpacetimeDB.Identity>(tableName, "OwnerIdentity");
            Team = new global::SpacetimeDB.Col<Champion, Team>(tableName, "Team");
            Name = new global::SpacetimeDB.Col<Champion, string>(tableName, "Name");
            Position = new global::SpacetimeDB.Col<Champion, DbVec3>(tableName, "Position");
            Destination = new global::SpacetimeDB.Col<Champion, DbVec3>(tableName, "Destination");
            MoveSpeed = new global::SpacetimeDB.Col<Champion, float>(tableName, "MoveSpeed");
            State = new global::SpacetimeDB.Col<Champion, ChampionState>(tableName, "State");
            Health = new global::SpacetimeDB.Col<Champion, float>(tableName, "Health");
            MaxHealth = new global::SpacetimeDB.Col<Champion, float>(tableName, "MaxHealth");
            Mana = new global::SpacetimeDB.Col<Champion, float>(tableName, "Mana");
            MaxMana = new global::SpacetimeDB.Col<Champion, float>(tableName, "MaxMana");
            AttackTargetKind = new global::SpacetimeDB.Col<Champion, TargetKind>(tableName, "AttackTargetKind");
            AttackTargetId = new global::SpacetimeDB.Col<Champion, ulong>(tableName, "AttackTargetId");
            LastAttackTime = new global::SpacetimeDB.Col<Champion, double>(tableName, "LastAttackTime");
            AttackRange = new global::SpacetimeDB.Col<Champion, float>(tableName, "AttackRange");
            AttackDamage = new global::SpacetimeDB.Col<Champion, float>(tableName, "AttackDamage");
            AttackCooldown = new global::SpacetimeDB.Col<Champion, float>(tableName, "AttackCooldown");
            DeathTime = new global::SpacetimeDB.Col<Champion, double>(tableName, "DeathTime");
            RespawnDuration = new global::SpacetimeDB.Col<Champion, float>(tableName, "RespawnDuration");
        }
    }

    public sealed class ChampionIxCols
    {
        public global::SpacetimeDB.IxCol<Champion, ulong> Id { get; }

        public ChampionIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<Champion, ulong>(tableName, "Id");
        }
    }
}
