// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ConfigHandle : RemoteTableHandle<EventContext, Config>
        {
            protected override string RemoteTableName => "Config";

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(Config row) => row.Id;

                public IdUniqueIndex(ConfigHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal ConfigHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(Config row) => row.Id;
        }

        public readonly ConfigHandle Config;
    }

    public sealed class ConfigCols
    {
        public global::SpacetimeDB.Col<Config, uint> Id { get; }
        public global::SpacetimeDB.Col<Config, float> MoveSpeed { get; }
        public global::SpacetimeDB.Col<Config, float> AttackRange { get; }
        public global::SpacetimeDB.Col<Config, float> AttackDamage { get; }
        public global::SpacetimeDB.Col<Config, float> AttackCooldown { get; }
        public global::SpacetimeDB.Col<Config, float> RespawnDuration { get; }
        public global::SpacetimeDB.Col<Config, float> ChampMaxHealth { get; }
        public global::SpacetimeDB.Col<Config, float> ChampMaxMana { get; }
        public global::SpacetimeDB.Col<Config, DbVec3> RadiantSpawn { get; }
        public global::SpacetimeDB.Col<Config, DbVec3> DireSpawn { get; }
        public global::SpacetimeDB.Col<Config, float> CreepMoveSpeed { get; }
        public global::SpacetimeDB.Col<Config, float> CreepAttackRange { get; }
        public global::SpacetimeDB.Col<Config, float> CreepAttackDamage { get; }
        public global::SpacetimeDB.Col<Config, float> CreepAttackCooldown { get; }
        public global::SpacetimeDB.Col<Config, float> CreepMaxHealth { get; }
        public global::SpacetimeDB.Col<Config, float> CreepWaveIntervalSec { get; }
        public global::SpacetimeDB.Col<Config, float> NeutralMoveSpeed { get; }
        public global::SpacetimeDB.Col<Config, float> NeutralAttackRange { get; }
        public global::SpacetimeDB.Col<Config, float> NeutralAttackDamage { get; }
        public global::SpacetimeDB.Col<Config, float> NeutralAttackCooldown { get; }
        public global::SpacetimeDB.Col<Config, float> NeutralMaxHealth { get; }
        public global::SpacetimeDB.Col<Config, float> NeutralRespawnSec { get; }
        public global::SpacetimeDB.Col<Config, float> TowerMaxHealth { get; }
        public global::SpacetimeDB.Col<Config, float> TowerAttackDamage { get; }
        public global::SpacetimeDB.Col<Config, float> TowerAttackRange { get; }
        public global::SpacetimeDB.Col<Config, float> TowerAttackCooldown { get; }
        public global::SpacetimeDB.Col<Config, float> ThroneMaxHealth { get; }

        public ConfigCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<Config, uint>(tableName, "Id");
            MoveSpeed = new global::SpacetimeDB.Col<Config, float>(tableName, "MoveSpeed");
            AttackRange = new global::SpacetimeDB.Col<Config, float>(tableName, "AttackRange");
            AttackDamage = new global::SpacetimeDB.Col<Config, float>(tableName, "AttackDamage");
            AttackCooldown = new global::SpacetimeDB.Col<Config, float>(tableName, "AttackCooldown");
            RespawnDuration = new global::SpacetimeDB.Col<Config, float>(tableName, "RespawnDuration");
            ChampMaxHealth = new global::SpacetimeDB.Col<Config, float>(tableName, "ChampMaxHealth");
            ChampMaxMana = new global::SpacetimeDB.Col<Config, float>(tableName, "ChampMaxMana");
            RadiantSpawn = new global::SpacetimeDB.Col<Config, DbVec3>(tableName, "RadiantSpawn");
            DireSpawn = new global::SpacetimeDB.Col<Config, DbVec3>(tableName, "DireSpawn");
            CreepMoveSpeed = new global::SpacetimeDB.Col<Config, float>(tableName, "CreepMoveSpeed");
            CreepAttackRange = new global::SpacetimeDB.Col<Config, float>(tableName, "CreepAttackRange");
            CreepAttackDamage = new global::SpacetimeDB.Col<Config, float>(tableName, "CreepAttackDamage");
            CreepAttackCooldown = new global::SpacetimeDB.Col<Config, float>(tableName, "CreepAttackCooldown");
            CreepMaxHealth = new global::SpacetimeDB.Col<Config, float>(tableName, "CreepMaxHealth");
            CreepWaveIntervalSec = new global::SpacetimeDB.Col<Config, float>(tableName, "CreepWaveIntervalSec");
            NeutralMoveSpeed = new global::SpacetimeDB.Col<Config, float>(tableName, "NeutralMoveSpeed");
            NeutralAttackRange = new global::SpacetimeDB.Col<Config, float>(tableName, "NeutralAttackRange");
            NeutralAttackDamage = new global::SpacetimeDB.Col<Config, float>(tableName, "NeutralAttackDamage");
            NeutralAttackCooldown = new global::SpacetimeDB.Col<Config, float>(tableName, "NeutralAttackCooldown");
            NeutralMaxHealth = new global::SpacetimeDB.Col<Config, float>(tableName, "NeutralMaxHealth");
            NeutralRespawnSec = new global::SpacetimeDB.Col<Config, float>(tableName, "NeutralRespawnSec");
            TowerMaxHealth = new global::SpacetimeDB.Col<Config, float>(tableName, "TowerMaxHealth");
            TowerAttackDamage = new global::SpacetimeDB.Col<Config, float>(tableName, "TowerAttackDamage");
            TowerAttackRange = new global::SpacetimeDB.Col<Config, float>(tableName, "TowerAttackRange");
            TowerAttackCooldown = new global::SpacetimeDB.Col<Config, float>(tableName, "TowerAttackCooldown");
            ThroneMaxHealth = new global::SpacetimeDB.Col<Config, float>(tableName, "ThroneMaxHealth");
        }
    }

    public sealed class ConfigIxCols
    {
        public global::SpacetimeDB.IxCol<Config, uint> Id { get; }

        public ConfigIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<Config, uint>(tableName, "Id");
        }
    }
}
