// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class CreepSpawnScheduleHandle : RemoteTableHandle<EventContext, CreepSpawnSchedule>
        {
            protected override string RemoteTableName => "CreepSpawnSchedule";

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(CreepSpawnSchedule row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(CreepSpawnScheduleHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal CreepSpawnScheduleHandle(DbConnection conn) : base(conn)
            {
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(CreepSpawnSchedule row) => row.ScheduledId;
        }

        public readonly CreepSpawnScheduleHandle CreepSpawnSchedule;
    }

    public sealed class CreepSpawnScheduleCols
    {
        public global::SpacetimeDB.Col<CreepSpawnSchedule, ulong> ScheduledId { get; }
        public global::SpacetimeDB.Col<CreepSpawnSchedule, SpacetimeDB.ScheduleAt> ScheduledAt { get; }

        public CreepSpawnScheduleCols(string tableName)
        {
            ScheduledId = new global::SpacetimeDB.Col<CreepSpawnSchedule, ulong>(tableName, "ScheduledId");
            ScheduledAt = new global::SpacetimeDB.Col<CreepSpawnSchedule, SpacetimeDB.ScheduleAt>(tableName, "ScheduledAt");
        }
    }

    public sealed class CreepSpawnScheduleIxCols
    {
        public global::SpacetimeDB.IxCol<CreepSpawnSchedule, ulong> ScheduledId { get; }

        public CreepSpawnScheduleIxCols(string tableName)
        {
            ScheduledId = new global::SpacetimeDB.IxCol<CreepSpawnSchedule, ulong>(tableName, "ScheduledId");
        }
    }
}
