// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class CreepHandle : RemoteTableHandle<EventContext, Creep>
        {
            protected override string RemoteTableName => "Creep";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Creep row) => row.Id;

                public IdUniqueIndex(CreepHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal CreepHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(Creep row) => row.Id;
        }

        public readonly CreepHandle Creep;
    }

    public sealed class CreepCols
    {
        public global::SpacetimeDB.Col<Creep, ulong> Id { get; }
        public global::SpacetimeDB.Col<Creep, Team> Team { get; }
        public global::SpacetimeDB.Col<Creep, CreepType> Type { get; }
        public global::SpacetimeDB.Col<Creep, Lane> Lane { get; }
        public global::SpacetimeDB.Col<Creep, DbVec3> Position { get; }
        public global::SpacetimeDB.Col<Creep, DbVec3> Destination { get; }
        public global::SpacetimeDB.Col<Creep, float> MoveSpeed { get; }
        public global::SpacetimeDB.Col<Creep, float> Health { get; }
        public global::SpacetimeDB.Col<Creep, float> MaxHealth { get; }
        public global::SpacetimeDB.Col<Creep, float> AttackRange { get; }
        public global::SpacetimeDB.Col<Creep, float> AttackDamage { get; }
        public global::SpacetimeDB.Col<Creep, float> AttackCooldown { get; }
        public global::SpacetimeDB.Col<Creep, CreepState> State { get; }
        public global::SpacetimeDB.Col<Creep, TargetKind> AttackTargetKind { get; }
        public global::SpacetimeDB.Col<Creep, ulong> AttackTargetId { get; }
        public global::SpacetimeDB.Col<Creep, double> LastAttackTime { get; }
        public global::SpacetimeDB.Col<Creep, double> DeathTime { get; }
        public global::SpacetimeDB.Col<Creep, ulong> CampId { get; }
        public global::SpacetimeDB.Col<Creep, int> WaypointIndex { get; }

        public CreepCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<Creep, ulong>(tableName, "Id");
            Team = new global::SpacetimeDB.Col<Creep, Team>(tableName, "Team");
            Type = new global::SpacetimeDB.Col<Creep, CreepType>(tableName, "Type");
            Lane = new global::SpacetimeDB.Col<Creep, Lane>(tableName, "Lane");
            Position = new global::SpacetimeDB.Col<Creep, DbVec3>(tableName, "Position");
            Destination = new global::SpacetimeDB.Col<Creep, DbVec3>(tableName, "Destination");
            MoveSpeed = new global::SpacetimeDB.Col<Creep, float>(tableName, "MoveSpeed");
            Health = new global::SpacetimeDB.Col<Creep, float>(tableName, "Health");
            MaxHealth = new global::SpacetimeDB.Col<Creep, float>(tableName, "MaxHealth");
            AttackRange = new global::SpacetimeDB.Col<Creep, float>(tableName, "AttackRange");
            AttackDamage = new global::SpacetimeDB.Col<Creep, float>(tableName, "AttackDamage");
            AttackCooldown = new global::SpacetimeDB.Col<Creep, float>(tableName, "AttackCooldown");
            State = new global::SpacetimeDB.Col<Creep, CreepState>(tableName, "State");
            AttackTargetKind = new global::SpacetimeDB.Col<Creep, TargetKind>(tableName, "AttackTargetKind");
            AttackTargetId = new global::SpacetimeDB.Col<Creep, ulong>(tableName, "AttackTargetId");
            LastAttackTime = new global::SpacetimeDB.Col<Creep, double>(tableName, "LastAttackTime");
            DeathTime = new global::SpacetimeDB.Col<Creep, double>(tableName, "DeathTime");
            CampId = new global::SpacetimeDB.Col<Creep, ulong>(tableName, "CampId");
            WaypointIndex = new global::SpacetimeDB.Col<Creep, int>(tableName, "WaypointIndex");
        }
    }

    public sealed class CreepIxCols
    {
        public global::SpacetimeDB.IxCol<Creep, ulong> Id { get; }

        public CreepIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<Creep, ulong>(tableName, "Id");
        }
    }
}
