// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class GameStateHandle : RemoteTableHandle<EventContext, GameState>
        {
            protected override string RemoteTableName => "GameState";

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(GameState row) => row.Id;

                public IdUniqueIndex(GameStateHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal GameStateHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(GameState row) => row.Id;
        }

        public readonly GameStateHandle GameState;
    }

    public sealed class GameStateCols
    {
        public global::SpacetimeDB.Col<GameState, uint> Id { get; }
        public global::SpacetimeDB.Col<GameState, GamePhase> Phase { get; }
        public global::SpacetimeDB.Col<GameState, Team> WinnerTeam { get; }
        public global::SpacetimeDB.Col<GameState, int> Countdown { get; }

        public GameStateCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<GameState, uint>(tableName, "Id");
            Phase = new global::SpacetimeDB.Col<GameState, GamePhase>(tableName, "Phase");
            WinnerTeam = new global::SpacetimeDB.Col<GameState, Team>(tableName, "WinnerTeam");
            Countdown = new global::SpacetimeDB.Col<GameState, int>(tableName, "Countdown");
        }
    }

    public sealed class GameStateIxCols
    {
        public global::SpacetimeDB.IxCol<GameState, uint> Id { get; }

        public GameStateIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<GameState, uint>(tableName, "Id");
        }
    }
}
