// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class GameTickScheduleHandle : RemoteTableHandle<EventContext, GameTickSchedule>
        {
            protected override string RemoteTableName => "GameTickSchedule";

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(GameTickSchedule row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(GameTickScheduleHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal GameTickScheduleHandle(DbConnection conn) : base(conn)
            {
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(GameTickSchedule row) => row.ScheduledId;
        }

        public readonly GameTickScheduleHandle GameTickSchedule;
    }

    public sealed class GameTickScheduleCols
    {
        public global::SpacetimeDB.Col<GameTickSchedule, ulong> ScheduledId { get; }
        public global::SpacetimeDB.Col<GameTickSchedule, SpacetimeDB.ScheduleAt> ScheduledAt { get; }

        public GameTickScheduleCols(string tableName)
        {
            ScheduledId = new global::SpacetimeDB.Col<GameTickSchedule, ulong>(tableName, "ScheduledId");
            ScheduledAt = new global::SpacetimeDB.Col<GameTickSchedule, SpacetimeDB.ScheduleAt>(tableName, "ScheduledAt");
        }
    }

    public sealed class GameTickScheduleIxCols
    {
        public global::SpacetimeDB.IxCol<GameTickSchedule, ulong> ScheduledId { get; }

        public GameTickScheduleIxCols(string tableName)
        {
            ScheduledId = new global::SpacetimeDB.IxCol<GameTickSchedule, ulong>(tableName, "ScheduledId");
        }
    }
}
