// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class LobbyPlayerHandle : RemoteTableHandle<EventContext, LobbyPlayer>
        {
            protected override string RemoteTableName => "LobbyPlayer";

            public sealed class PlayerIdUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(LobbyPlayer row) => row.PlayerId;

                public PlayerIdUniqueIndex(LobbyPlayerHandle table) : base(table) { }
            }

            public readonly PlayerIdUniqueIndex PlayerId;

            internal LobbyPlayerHandle(DbConnection conn) : base(conn)
            {
                PlayerId = new(this);
            }

            protected override object GetPrimaryKey(LobbyPlayer row) => row.PlayerId;
        }

        public readonly LobbyPlayerHandle LobbyPlayer;
    }

    public sealed class LobbyPlayerCols
    {
        public global::SpacetimeDB.Col<LobbyPlayer, SpacetimeDB.Identity> PlayerId { get; }
        public global::SpacetimeDB.Col<LobbyPlayer, string> Name { get; }
        public global::SpacetimeDB.Col<LobbyPlayer, Team> Team { get; }
        public global::SpacetimeDB.Col<LobbyPlayer, bool> IsReady { get; }
        public global::SpacetimeDB.Col<LobbyPlayer, bool> IsConnected { get; }

        public LobbyPlayerCols(string tableName)
        {
            PlayerId = new global::SpacetimeDB.Col<LobbyPlayer, SpacetimeDB.Identity>(tableName, "PlayerId");
            Name = new global::SpacetimeDB.Col<LobbyPlayer, string>(tableName, "Name");
            Team = new global::SpacetimeDB.Col<LobbyPlayer, Team>(tableName, "Team");
            IsReady = new global::SpacetimeDB.Col<LobbyPlayer, bool>(tableName, "IsReady");
            IsConnected = new global::SpacetimeDB.Col<LobbyPlayer, bool>(tableName, "IsConnected");
        }
    }

    public sealed class LobbyPlayerIxCols
    {
        public global::SpacetimeDB.IxCol<LobbyPlayer, SpacetimeDB.Identity> PlayerId { get; }

        public LobbyPlayerIxCols(string tableName)
        {
            PlayerId = new global::SpacetimeDB.IxCol<LobbyPlayer, SpacetimeDB.Identity>(tableName, "PlayerId");
        }
    }
}
