// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class StructureHandle : RemoteTableHandle<EventContext, Structure>
        {
            protected override string RemoteTableName => "Structure";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Structure row) => row.Id;

                public IdUniqueIndex(StructureHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal StructureHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(Structure row) => row.Id;
        }

        public readonly StructureHandle Structure;
    }

    public sealed class StructureCols
    {
        public global::SpacetimeDB.Col<Structure, ulong> Id { get; }
        public global::SpacetimeDB.Col<Structure, Team> Team { get; }
        public global::SpacetimeDB.Col<Structure, StructureType> Type { get; }
        public global::SpacetimeDB.Col<Structure, Lane> Lane { get; }
        public global::SpacetimeDB.Col<Structure, DbVec3> Position { get; }
        public global::SpacetimeDB.Col<Structure, float> Health { get; }
        public global::SpacetimeDB.Col<Structure, float> MaxHealth { get; }
        public global::SpacetimeDB.Col<Structure, float> AttackDamage { get; }
        public global::SpacetimeDB.Col<Structure, float> AttackRange { get; }
        public global::SpacetimeDB.Col<Structure, float> AttackCooldown { get; }
        public global::SpacetimeDB.Col<Structure, double> LastAttackTime { get; }
        public global::SpacetimeDB.Col<Structure, ulong> AttackTargetId { get; }
        public global::SpacetimeDB.Col<Structure, TargetKind> AttackTargetKind { get; }
        public global::SpacetimeDB.Col<Structure, bool> IsDestroyed { get; }

        public StructureCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<Structure, ulong>(tableName, "Id");
            Team = new global::SpacetimeDB.Col<Structure, Team>(tableName, "Team");
            Type = new global::SpacetimeDB.Col<Structure, StructureType>(tableName, "Type");
            Lane = new global::SpacetimeDB.Col<Structure, Lane>(tableName, "Lane");
            Position = new global::SpacetimeDB.Col<Structure, DbVec3>(tableName, "Position");
            Health = new global::SpacetimeDB.Col<Structure, float>(tableName, "Health");
            MaxHealth = new global::SpacetimeDB.Col<Structure, float>(tableName, "MaxHealth");
            AttackDamage = new global::SpacetimeDB.Col<Structure, float>(tableName, "AttackDamage");
            AttackRange = new global::SpacetimeDB.Col<Structure, float>(tableName, "AttackRange");
            AttackCooldown = new global::SpacetimeDB.Col<Structure, float>(tableName, "AttackCooldown");
            LastAttackTime = new global::SpacetimeDB.Col<Structure, double>(tableName, "LastAttackTime");
            AttackTargetId = new global::SpacetimeDB.Col<Structure, ulong>(tableName, "AttackTargetId");
            AttackTargetKind = new global::SpacetimeDB.Col<Structure, TargetKind>(tableName, "AttackTargetKind");
            IsDestroyed = new global::SpacetimeDB.Col<Structure, bool>(tableName, "IsDestroyed");
        }
    }

    public sealed class StructureIxCols
    {
        public global::SpacetimeDB.IxCol<Structure, ulong> Id { get; }

        public StructureIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<Structure, ulong>(tableName, "Id");
        }
    }
}
