// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class UserProfileHandle : RemoteTableHandle<EventContext, UserProfile>
        {
            protected override string RemoteTableName => "UserProfile";

            public sealed class PlayerIdUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(UserProfile row) => row.PlayerId;

                public PlayerIdUniqueIndex(UserProfileHandle table) : base(table) { }
            }

            public readonly PlayerIdUniqueIndex PlayerId;

            public sealed class UsernameUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(UserProfile row) => row.Username;

                public UsernameUniqueIndex(UserProfileHandle table) : base(table) { }
            }

            public readonly UsernameUniqueIndex Username;

            internal UserProfileHandle(DbConnection conn) : base(conn)
            {
                PlayerId = new(this);
                Username = new(this);
            }

            protected override object GetPrimaryKey(UserProfile row) => row.PlayerId;
        }

        public readonly UserProfileHandle UserProfile;
    }

    public sealed class UserProfileCols
    {
        public global::SpacetimeDB.Col<UserProfile, SpacetimeDB.Identity> PlayerId { get; }
        public global::SpacetimeDB.Col<UserProfile, string> Username { get; }

        public UserProfileCols(string tableName)
        {
            PlayerId = new global::SpacetimeDB.Col<UserProfile, SpacetimeDB.Identity>(tableName, "PlayerId");
            Username = new global::SpacetimeDB.Col<UserProfile, string>(tableName, "Username");
        }
    }

    public sealed class UserProfileIxCols
    {
        public global::SpacetimeDB.IxCol<UserProfile, SpacetimeDB.Identity> PlayerId { get; }
        public global::SpacetimeDB.IxCol<UserProfile, string> Username { get; }

        public UserProfileIxCols(string tableName)
        {
            PlayerId = new global::SpacetimeDB.IxCol<UserProfile, SpacetimeDB.Identity>(tableName, "PlayerId");
            Username = new global::SpacetimeDB.IxCol<UserProfile, string>(tableName, "Username");
        }
    }
}
